# Generated by Django 3.1 on 2021-02-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_auto_20210201_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(max_length=350, null=True),
        ),
    ]
